### ISSUE TITLE
Replace old Animation Code with Sausage64

### ISSUE THREAD

**Issue by Byterset** [Byterset/n64brew#4]
The old animation code should be replaced with the newly adopted Sausage64 library. Old Model exports should be re-exported via the appropriate tools and the old exports & tools removed

**Comment by Byterset** [comment]
resolving this issue includes:

- removing the old animation code
- remove legacy tools for animation export and eventually include sausage64 tools
- handle animated objects in level file structure separately

**Comment by buu342** [comment]
Just a heads up that Sausage64 had a big update recently which adds in binary model asset support (As well as a lot of new features). Might be worth pulling in the new changes :slightly_smiling_face:

**Comment by Byterset** [comment]
@buu342 thanks for the heads up :) I created Issue #12  for that and will have a look at the updates!
